name: bech32m
version: 0.2.1-1
description: Library implementing Bitcoins BIP350 (Bech32m encoding) specification in a Flutter friendly fashion.
homepage: https://github.com/joaquimguimaraes/bech32m

dependencies:
    convert: '>=1.0.0 <3.1.0'
    hex: ^0.2.0

dev_dependencies:
    pedantic: ^1.11.0
    test: ^1.16.5

environment:
  sdk: ">=2.12.0 <3.0.0"
